In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [28]:
data =  open("datasetTextosEmPortugues.txt", encoding="utf-8")
meuTexto = data.read()

In [29]:
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([meuTexto])
total_words = len(mytokenizer.word_index) + 1

In [30]:
mytokenizer.word_index

{'de': 1,
 'a': 2,
 'que': 3,
 'e': 4,
 'o': 5,
 'da': 6,
 'do': 7,
 'um': 8,
 'se': 9,
 'é': 10,
 'em': 11,
 'não': 12,
 'uma': 13,
 'para': 14,
 'com': 15,
 'eu': 16,
 'por': 17,
 'as': 18,
 'os': 19,
 'como': 20,
 'na': 21,
 'mais': 22,
 'ou': 23,
 'no': 24,
 'das': 25,
 'sua': 26,
 'ao': 27,
 'entre': 28,
 'ser': 29,
 'mas': 30,
 'são': 31,
 'vida': 32,
 'pode': 33,
 'muito': 34,
 'mesmo': 35,
 'nos': 36,
 'características': 37,
 'seu': 38,
 'homem': 39,
 'pelo': 40,
 'isso': 41,
 'à': 42,
 'deus': 43,
 'foi': 44,
 'social': 45,
 'sociais': 46,
 'ele': 47,
 'dos': 48,
 'me': 49,
 'cada': 50,
 'mídias': 51,
 'evolução': 52,
 'tempo': 53,
 'kierkegaard': 54,
 'fé': 55,
 'podem': 56,
 'até': 57,
 'verdade': 58,
 'genes': 59,
 'pessoas': 60,
 'tudo': 61,
 'já': 62,
 'você': 63,
 'também': 64,
 'apenas': 65,
 'mídia': 66,
 'sou': 67,
 'cristo': 68,
 'histórias': 69,
 'através': 70,
 'era': 71,
 'sobre': 72,
 'qual': 73,
 'seus': 74,
 '8': 75,
 'pela': 76,
 'quando': 77,
 'porque': 78,
 

In [31]:
my_input_sequences = []
for line in meuTexto.split('\n'):
    #print(line)
    token_list = mytokenizer.texts_to_sequences([line])[0]
    #print(token_list)
    for i in range(1, len(token_list)):
        my_n_gram_sequence = token_list[:i+1]
        #print(my_n_gram_sequence)
        my_input_sequences.append(my_n_gram_sequence)
        #print(input_sequences)

In [19]:
max_sequence_len = max([len(seq) for seq in my_input_sequences])
input_sequences = np.array(pad_sequences(my_input_sequences, maxlen=max_sequence_len, padding='pre'))

In [20]:
input_sequences[1]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [21]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [32]:
X[1]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [23]:
y

array([ 123,  720,    1, ..., 2136,    4, 2137])

In [33]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=total_words))

In [34]:
y[1]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [35]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(LSTM(150))
model.add(Dense(total_words, activation='softmax'))
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 427, 100)          213800    
                                                                 
 lstm_1 (LSTM)               (None, 150)               150600    
                                                                 
 dense_1 (Dense)             (None, 2138)              322838    
                                                                 
Total params: 687238 (2.62 MB)
Trainable params: 687238 (2.62 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [36]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=50, verbose=1)

Epoch 1/50
202/202 [==============================] - 184s 909ms/step - loss: 6.8974 - accuracy: 0.0413
Epoch 2/50
202/202 [==============================] - 208s 1s/step - loss: 6.3695 - accuracy: 0.0458
Epoch 3/50
202/202 [==============================] - 214s 1s/step - loss: 6.2229 - accuracy: 0.0525
Epoch 4/50
202/202 [==============================] - 220s 1s/step - loss: 6.0985 - accuracy: 0.0569
Epoch 5/50
202/202 [==============================] - 224s 1s/step - loss: 5.9656 - accuracy: 0.0622
Epoch 6/50
202/202 [==============================] - 234s 1s/step - loss: 5.8246 - accuracy: 0.0676
Epoch 7/50
202/202 [==============================] - 236s 1s/step - loss: 5.6764 - accuracy: 0.0760
Epoch 8/50
202/202 [==============================] - 240s 1s/step - loss: 5.4991 - accuracy: 0.0861
Epoch 9/50
202/202 [==============================] - 239s 1s/step - loss: 5.3004 - accuracy: 0.0987
Epoch 10/50
202/202 [==============================] - 249s 1s/step - loss: 5.0797 - acc

In [37]:
model.save('modelo_LSVM.h5')

c:\Users\Yuri Getaruck\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [83]:
input_text = "ontem eu queria"
predict_next_words= 1

for _ in range(predict_next_words):
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    print(token_list)
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

[622, 16, 1720]
1/1 [==============================] - 0s 39ms/step
ontem eu queria nem


In [72]:
import re

# Abrindo o arquivo e lendo o texto com a codificação 'utf-8'
with open('DBpediaRelations-PT-0.2.txt', 'r', encoding='utf-8') as file:
    texto = file.read()

# Usando regex para encontrar as sentenças únicas
sentences = re.findall(r'SENTENCE : (.*?)\n', texto, re.DOTALL)

# Removendo duplicatas utilizando um conjunto (set)
sentences_unique = set(sentences)

# Juntando as sentenças únicas encontradas em um novo texto
novo_texto = '\n'.join(sentences_unique)

# Escrevendo as sentenças únicas em um novo arquivo
with open('sentencas_sem_duplicatas.txt', 'w', encoding='utf-8') as file:
    file.write(novo_texto)

print("As sentenças únicas foram salvas em 'sentencas_sem_duplicatas.txt'")



As sentenças únicas foram salvas em 'sentencas_sem_duplicatas.txt'


In [74]:
from keras.models import load_model

modelosalvo = load_model('modelo_LSVM.h5')