In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [2]:
data =  open("sentencas_sem_duplicatas.txt", encoding="utf-8")
meuTexto = data.read()

In [3]:
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([meuTexto])
total_words = len(mytokenizer.word_index) + 1

In [4]:
mytokenizer.word_index

{'de': 1,
 'é': 2,
 'no': 3,
 'do': 4,
 'e': 5,
 'um': 6,
 'da': 7,
 'uma': 8,
 'estado': 9,
 'a': 10,
 'em': 11,
 'o': 12,
 'localizada': 13,
 'condado': 14,
 'americano': 15,
 'na': 16,
 'cidade': 17,
 'município': 18,
 'com': 19,
 'que': 20,
 'norte': 21,
 'brasileiro': 22,
 'km²': 23,
 'foi': 24,
 'como': 25,
 'província': 26,
 'rio': 27,
 'região': 28,
 'são': 29,
 'habitantes': 30,
 'comunidade': 31,
 'área': 32,
 'espanha': 33,
 'autónoma': 34,
 'população': 35,
 'mais': 36,
 'densidade': 37,
 'populacional': 38,
 'hab': 39,
 'dos': 40,
 'janeiro': 41,
 'futebolista': 42,
 'se': 43,
 'localizado': 44,
 'distrito': 45,
 'por': 46,
 'paulo': 47,
 'conhecido': 48,
 '2007': 49,
 'sul': 50,
 'para': 51,
 '—': 52,
 'banda': 53,
 'vila': 54,
 'censo': 55,
 'designada': 56,
 'brasileira': 57,
 'ao': 58,
 'grande': 59,
 'das': 60,
 'maio': 61,
 'março': 62,
 'futebol': 63,
 'os': 64,
 'sua': 65,
 'à': 66,
 'comuna': 67,
 'junho': 68,
 'abril': 69,
 'dezembro': 70,
 'outubro': 71,
 'brasi

In [5]:
my_input_sequences = []
for line in meuTexto.split('\n'):
    #print(line)
    token_list = mytokenizer.texts_to_sequences([line])[0]
    #print(token_list)
    for i in range(1, len(token_list)):
        my_n_gram_sequence = token_list[:i+1]
        #print(my_n_gram_sequence)
        my_input_sequences.append(my_n_gram_sequence)
        #print(input_sequences)

In [6]:
max_sequence_len = max([len(seq) for seq in my_input_sequences])
input_sequences = np.array(pad_sequences(my_input_sequences, maxlen=max_sequence_len, padding='pre'))

In [7]:
input_sequences[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [8]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [9]:
X[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [10]:
y

array([1030,    2,    6, ...,  361,    1,  433])

In [11]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=total_words))

In [12]:
y[1]

array([0., 0., 1., ..., 0., 0., 0.], dtype=float32)

In [13]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(LSTM(150))
model.add(Dense(total_words, activation='softmax'))
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 190, 100)          2609800   
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 26098)             3940798   
                                                                 
Total params: 6701198 (25.56 MB)
Trainable params: 6701198 (25.56 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [14]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=10, verbose=1)

Epoch 1/10
6695/6695 [==============================] - 1443s 215ms/step - loss: 5.1927 - accuracy: 0.3162
Epoch 2/10
6695/6695 [==============================] - 1469s 219ms/step - loss: 4.0074 - accuracy: 0.4068
Epoch 3/10
6695/6695 [==============================] - 1450s 217ms/step - loss: 3.5231 - accuracy: 0.4362
Epoch 4/10
6695/6695 [==============================] - 1431s 214ms/step - loss: 3.1121 - accuracy: 0.4627
Epoch 5/10
6695/6695 [==============================] - 1424s 213ms/step - loss: 2.7370 - accuracy: 0.4913
Epoch 6/10
6695/6695 [==============================] - 1882s 281ms/step - loss: 2.4001 - accuracy: 0.5292
Epoch 7/10
6695/6695 [==============================] - 1877s 280ms/step - loss: 2.1039 - accuracy: 0.5711
Epoch 8/10
6695/6695 [==============================] - 1887s 282ms/step - loss: 1.8543 - accuracy: 0.6120
Epoch 9/10
6695/6695 [==============================] - 2029s 303ms/step - loss: 1.6413 - accuracy: 0.6499
Epoch 10/10
6695/6695 [==============

In [15]:
model.save('modelo_LSVM2.h5')

c:\Users\Yuri Getaruck\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [22]:
input_text = "eu gosto"
predict_next_words= 1

for _ in range(predict_next_words):
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    print(token_list)
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

[4987, 8977]
1/1 [==============================] - 0s 18ms/step
eu gosto pela


In [72]:
import re

# Abrindo o arquivo e lendo o texto com a codificação 'utf-8'
with open('DBpediaRelations-PT-0.2.txt', 'r', encoding='utf-8') as file:
    texto = file.read()

# Usando regex para encontrar as sentenças únicas
sentences = re.findall(r'SENTENCE : (.*?)\n', texto, re.DOTALL)

# Removendo duplicatas utilizando um conjunto (set)
sentences_unique = set(sentences)

# Juntando as sentenças únicas encontradas em um novo texto
novo_texto = '\n'.join(sentences_unique)

# Escrevendo as sentenças únicas em um novo arquivo
with open('sentencas_sem_duplicatas.txt', 'w', encoding='utf-8') as file:
    file.write(novo_texto)

print("As sentenças únicas foram salvas em 'sentencas_sem_duplicatas.txt'")



As sentenças únicas foram salvas em 'sentencas_sem_duplicatas.txt'
